### ISSUE TITLE
ERROR: Value of indmiss argument should be between 0 and 1.

### ISSUE THREAD

**Issue by laninsky** [mennodejong1986/SambaR#11]
When setting indmiss=1 and/or snpmiss=0, filterdata fails with the following error (for example for indmiss):
```
ERROR: Value of indmiss argument should be between 0 and 1.
```
I have a situation where I do not want to drop any of my individuals, so I need to set indmiss to 1. This error is due to the following code in SAMBAR_v1.0.4:
```
	if(indmiss>=1|indmiss<=0)
		{
		return(cat("ERROR: Value of indmiss argument should be between 0 and 1.",sep="\n"))
		}
	if(snpmiss>=1|snpmiss<=0)
		{
		return(cat("ERROR: Value of snpmiss argument should be between 0 and 1.",sep="\n"))
```
If modified to (i.e. the greater/less than equals are changed to greater/less than):
```
	if(indmiss>1|indmiss<0)
		{
		return(cat("ERROR: Value of indmiss argument should be between 0 and 1.",sep="\n"))
		}
	if(snpmiss>1|snpmiss<0)
		{
		return(cat("ERROR: Value of snpmiss argument should be between 0 and 1.",sep="\n"))
		}
```
Then it runs fine. Not sure if there is a reason why it should actually be greater/less than equal in this function, so thought I'd flag it as a potential issue. Thanks for this neat package!

**Comment by mennodejong1986** [comment]
Thanks for the feedback. The initial reason for setting it to >= rather than > seems not to exist any longer, so I changed it now in the new version which I uploaded today.
