### ISSUE TITLE
Columns of genlight obj don't correspond to snps$genlightname column

### ISSUE THREAD

**Issue by alexkrohn** [mennodejong1986/SambaR#12]
Hi there,

I'm not sure why I'm getting this error, and the error says to contact a developer of SambaR.

`ERROR: column names of genlight object do not correspond with snps$genlightname column. Contact developer of SambaR.`

My data (.RAW + .BIM) and pop file are attached. Please let me know if you need more information.

The VCF came from iPyRAD, which I then filtered for depth, and then removed a few low quality individuals. I converted the resulting vcf to PED using vcftools, and then to RAW/BIM using Plink2 as instructed. One irregularity that I noticed was that the starting VCF (also attached) kept 6138 sites after filtering, but only 5954 sites passed filters and QC when converting to PED. Not sure if that helps in the detective work.

Please let me know if you need more information.

Thanks for your help,

Alex
[filtered-vcf-sites-and-inds.bim.gz](https://github.com/mennodejong1986/SambaR/files/6729257/filtered-vcf-sites-and-inds.bim.gz)
[filtered-vcf-sites-and-inds.raw.gz](https://github.com/mennodejong1986/SambaR/files/6729258/filtered-vcf-sites-and-inds.raw.gz)
[popfile-filtered-vcf.txt.gz](https://github.com/mennodejong1986/SambaR/files/6729259/popfile-filtered-vcf.txt.gz)
[mate-inds-sites-filtered.recode.vcf.gz](https://github.com/mennodejong1986/SambaR/files/6729270/mate-inds-sites-filtered.recode.vcf.gz)

**Comment by mennodejong1986** [comment]
Hi Alex,

I did not manage to reproduce your error with the newly uploaded script and the following commands:

mycolours		<- c("blue","darkgreen","darkred","orange","darkorchid4","indianred1","deepskyblue","greenyellow","#654321","#009595","gray20","gray50","gray80","midnightblue","lavenderblush3","ivory2","aquamarine4","burlywood4","gray10","gray30","gray60","gray70","gray85","gray95")
	
importdata(inputprefix="filtered-vcf-sites-and-inds",samplefile="popfile-filteredvcf.txt",sumstatsfile=FALSE,depthfile=FALSE,colourvector=mycolours)

filterdata(indmiss=0.85,snpmiss=0.5)

findstructure()

calcdistance()

calcdiversity()

When exactly did the error occur?

**Comment by alexkrohn** [comment]
Hmm! Interesting. I ran `importdata()` with `depthfile=TRUE` because I had run `vcftools --depth` earlier. Now that I change `depthfile = FALSE` it works well. I guess that's what was throwing the error. Thanks for your help!
