### ISSUE TITLE
Problem creating RAW file

### ISSUE THREAD

**Issue by tomas-fer** [mennodejong1986/SambaR#15]
Hello,
I have a problem creating RAW file using PLINK. I have my VCF.GZ file which I successfully used to create ped and map files.
However, when using plink v1.07 in Linux (Fedora 34), I have trouble using the command from SambaR manual:
`plink --file prefix –-chr-set 95 –-allow-extra-chr --make-bed --recode A --out prefix`
There is no such option `–-chr-set 95` and `–-allow-extra-chr`, see
[http://zzz.bwh.harvard.edu/plink/reference.shtml#options](http://zzz.bwh.harvard.edu/plink/reference.shtml#options)
Moreover, the option `--recode A` should be `--recodeA`?
However, now `*.raw` file is created?
Could you help me with this, please?
Thank you,
Tomas

**Comment by mennodejong1986** [comment]
Hi Tomas,
I suppose the available options depend on the version of plink you are using. 
If --chr-set and --allow-extra-chr are not needed, just omit them.
Looks like the option '--recodeA' should indeed create the raw file. 
What does the screen output tell?
Best,
Menno

**Comment by tomas-fer** [comment]
Dear Menno,
I am sorry for this issue. By mistake, I used a very old [original PLINK version](https://zzz.bwh.harvard.edu/plink/index.shtml) instead of the [new plink2](https://www.cog-genomics.org/plink2) (referenced in your manual). Everything is working now, I was able to create RAW file and import data to SambaR. Maybe you can add a warning to your manual that users should avoid using old PLINK as this does not work.
Thank you and best wishes,
Tomas
