### ISSUE TITLE
Issue with z scores for d statistics

### ISSUE THREAD

**Issue by gspellman** [mennodejong1986/SambaR#17]
Hello,

I receive the following error when I run d statistic analysis in the calcdistance function:

WARNING: Input dataframe does not contain a column named 'sign' for significance. Assigning all data points same pch symbol.
Error in round(mydf$D_Z, 1) : 
  non-numeric argument to mathematical function
In addition: Warning message:
In fttDescision(ftt, "SIGNIFICANT", TripletCombinations, dna) :
 
 Error in round(mydf$D_Z, 1) : 
non-numeric argument to mathematical function

Any help would be appreciated.

**Comment by gspellman** [comment]
I realize I am not getting a column named 'sign' but I can't figure out why.

**Comment by mennodejong1986** [comment]
Thanks for reporting the issue.
To better understand what causes the problem, could you run the following two commands and report the complete screen output?

source("https://github.com/mennodejong1986/SambaR/raw/master/SAMBAR_v1.06.txt")
calcdistance(silent=FALSE,only_geneflow=TRUE)

**Comment by gspellman** [comment]
After running your recommended scripts, this is what I get.

REMINDER: if you receive an error stating 'cannot open file' (without the addition 'No such file or directory') this is likely because the file is opened in another file viewer.
If so, close the relevant file in the file viewer and try again.
Calculating ABBA-BABA statistics...
A table with D-statistics (called 'Dstatistics.txt') has been exported to the directory:
C:/Users/garth/Documents/House Wren data/SambaR_output/Divergence
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
WARNING: NA-values present in 'sign'-column of D-scores dataframe. Using the x-symbol to represent D-scores with unknown significance scores.
Analysis finished.

**Comment by mennodejong1986** [comment]
At least this time it seems have to finished without fatal errors.

It still complains about the missing significance columns. Does your data contain information regarding the position of snps within the genome? If not, division of the SNPs into blocks of 1Mb width might not work as intended, with one possible outcome being a low number of blocks (too low for meaningful jackknife resampling. 

I made some changes in the script to make the user aware of this potential issue. It will output on the screen the number of blocks in which the genome has been divided. If below 50, or any other user-defined value, jackknifing is omitted, and as a result a column with p-values will be absent from the output dataframe. 

To find out if this solves your problem, you could try these commands:

source("https://github.com/mennodejong1986/SambaR/raw/master/SAMBAR_v1.06.txt")
calcdistance(silent=FALSE,only_geneflow=TRUE,do_jackknife=TRUE,minjkblocks=50)

**Comment by gspellman** [comment]
I am working with ddRAD data. So I do not have genomic position data. I guess that is the problem. Is there a potential work around?

**Comment by mennodejong1986** [comment]
If you generated your SNPs using reference-based genotype calling pipeline (e.g., STACKS refmap), you should have positional information. 
If not (i.e., in case you use a de novo method), I guess that is still not too much of a problem. You would simply assume that snps from different read pairs are unlinked. Did you already find out in how many blocks your genome is divided? I built in a new option to adjust this value by setting the block size (default is 1 Mb):

source("https://github.com/mennodejong1986/SambaR/raw/master/SAMBAR_v1.06.txt")
calcdistance(silent=FALSE,only_geneflow=TRUE,do_jackknife=TRUE,minjkblocks=50,jk_blocksize=1000000)

I furthermore made a change in the script which should prevent NA-values in the sign-column.

**Comment by gspellman** [comment]
Output says my genome is in 1 block. Obviously I am lacking positional data and therefore the jackknife is not possible. We used a de novo method. I do assume that the SNPs are unlinked.

**Comment by mennodejong1986** [comment]
Which values are present in the columns snps$chr and snps$pos (see also input map-file)? 

If these columns contain locus names and locus positions (rather than chromosome/scaffold names and positions), the Dstats-function would in theory assign one block per locus. 

If, alternatively, only one unique value is present in the snps$chr column, adjustment of the block_size argument (smaller block sizes) should increase the number of blocks.

**Comment by gspellman** [comment]
Changing the block size solved the issue!

Thank you for all your help!

**Comment by mennodejong1986** [comment]
Great! Thanks for reporting the issue.
