### ISSUE TITLE
SambaR not creating snp and inds dataframe

### ISSUE THREAD

**Issue by TaylorLBurke** [mennodejong1986/SambaR#2]
I have followed the instructions in the manual, however, after importing my data the only object generated in the mygenlight object. Below I have pasted my exact script. What should I do to get the command to successfully create the other two dataframes? Since it did not work, should I just create a text file that lists my samples and the number of loci (however, this will likely be different than the loc.names list.)? Please advise! 

#POPULATION ANALYSES
#SambaR
#datamm30

#Installing SambaR and setting working directory
source("/Users/taylorburke/Documents/MSc_Thesis/PROGRAMS/SambaR-master/SAMBAR_v1.01.txt")
getpackages(myrepos='http://cran.us.r-project.org',mylib=NULL)
setwd("~/Documents/MSc_Thesis/Data/Data")

#Import Data
importdata(inputprefix='filter6_mm30',geofile="geofile.txt",depthfile = TRUE)

<img width="858" alt="Screen Shot 2021-01-30 at 9 38 11 PM" src="https://user-images.githubusercontent.com/78272985/106363685-79a8db00-6343-11eb-90ec-4deaeb097957.png">

Thank you,
Taylor

**Comment by TaylorLBurke** [comment]
I should add that I imported my data from a RAW file

**Comment by mennodejong1986** [comment]
Hi Taylor, thanks for your message. The screen output indicates that one or more population names contain an underscore. SambaR does not accept that and therefore aborted. The easiest solution is to create a sample file indeed. It does not matter that the population names in this file are not identical to the population names in the ped (and hence raw) file. See the manual for more instructions about how to generate a correct sample file. Best, Menno

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by TaylorLBurke** [comment]
Hi Menno! 

Perfect- thank you for your input! This worked and fixed the issues. 

Cheers,
Taylor

**Comment by bibi1313** [comment]
Hey,
I couldn't find the instructions on how to create a sample file in the manual.
I have the exact same issue as @TaylorLBurke .
@mennodejong1986 can you help?

**Comment by mennodejong1986** [comment]
Hi,

The sample file is simply a tab delimited file with at minimum two columns, named ‘name’ and ‘pop’.
The first column contains the sample name and the second column contains the population name.

I will make this information more visible in the manual.
Hope that helps!


Verzonden vanuit Outlook<http://aka.ms/weboutlook>

________________________________
Van: bibi1313 ***@***.***>
Verzonden: dinsdag 14 februari 2023 20:04
Aan: mennodejong1986/SambaR ***@***.***>
CC: mennodejong1986 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [mennodejong1986/SambaR] SambaR not creating snp and inds dataframe (#2)


Hey,
I couldn't find the instructions on how to create a sample file in the manual.
I have the exact same issue as @TaylorLBurke<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTaylorLBurke&data=05%7C01%7C%7Cc114fe8f958e4612fc9108db0ec6b6d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638120018851843835%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ugbABs%2FS92XNCaDnSoTshRbgQE%2BjfyEzT5b5IUMTe%2Bo%3D&reserved=0> .
@mennodejong1986<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmennodejong1986&data=05%7C01%7C%7Cc114fe8f958e4612fc9108db0ec6b6d7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638120018851843835%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FY6EIQoO2LXw7Bmly9MeBXE%2FVJbKeqneFu5XwrcnorE%3D&reserved=0> can you help?

**Comment by bibi1313** [comment]
Thank you!
I got it.

I have another question….
How can I get the numerical values that resulted in the figures?

For example, I got the boxplot attached for % heterozygosity.
How can I get the numerical values and average for the % heterozygosity?

￼
Thank you,
Anna

**Comment by mennodejong1986** [comment]
Hi Anna,

Most data is stored in the inds or snps dataframe.
For example, the heterozygosity values can be found in the column 'inds$hetero_all'.

Hope that helps!


Verzonden vanuit Outlook<http://aka.ms/weboutlook>

________________________________
Van: bibi1313 ***@***.***>
Verzonden: vrijdag 24 februari 2023 12:40
Aan: mennodejong1986/SambaR ***@***.***>
CC: mennodejong1986 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [mennodejong1986/SambaR] SambaR not creating snp and inds dataframe (#2)


Thank you!
I got it.

I have another question….
How can I get the numerical values that resulted in the figures?

For example, I got the boxplot attached for % heterozygosity.
How can I get the numerical values and average for the % heterozygosity?

￼
Thank you,
Anna

**Comment by bibi1313** [comment]
Hello!
It worked. Thank you very much!

Another question:
When I enter 'inds$hetero_all’ I get a different value for each individual, whereas when I type “inds$expHe_all” I get the same value for each ind.
To get the hetero for the pop should I do an average of those values or there is another code to derive the value?
Please find an image of the R console attached to this email.

Thank you,
Anna

￼
