### ISSUE TITLE
Can't figure out how to use latitude/longitude because I need to use genlight format to import my data

### ISSUE THREAD

**Issue by bmillerlab** [mennodejong1986/SambaR#25]
Hello,
First thanks for all the help so far (with the calcMLH and other problems).

Second, I have a vcf dataset that absolutely won't go into sambar except through the genlight option (I have checked with my service provider and I think the problem is with the format of vcf files output by BBTools).  I can get the data into sambar using the genlight2sambar option, but I can't figure out any way to enter data like the "geofile" option I used before under the normal importdata() command into the dataset.  I really need to consider lat/long with this data, so is there any way that would be possible?

Thank you!

**Comment by mennodejong1986** [comment]
Indeed I still need to update the manual regarding this topic.

After importing the data (either with genlight2sambar or importdata function), you can use the add2inds() function to add additional information to the inds dataframe. (In older versions of SambaR this function was called 'addsampleinfo'). 

For example, if in your working directory you have a file called 'sampleinfo.txt', which contains the columns 'name', 'longitude' and 'latitude', you can incorporate this information by running the command:

add2inds(samplefile="sampleinfo.txt")

In case the columns longitude and latitude are present in the sampleinfo.txt file, the add2inds function will also calculate geographic distances for each sample pair and add this information to the inds2 dataframe.

Afterwards, you can run the createmaps() function to generate geographical maps.

**Comment by bmillerlab** [comment]
Hi, Thanks once again.  This worked great!
