### ISSUE TITLE
unable to add Bayescan output

### ISSUE THREAD

**Issue by mimingcui** [mennodejong1986/SambaR#28]
Hi! I'm glad that I stumbled onto this all-in-one R package for population genetics analyses. The user manual is very detailed. Way to go! It'd be so convinient if eventally all the bugs will be fixed. I hope it will gain more users.

I'm currently running selection analysis and added the Bayescan output in the SambaR inputfiles directory as 
`./myWorkDir/SambaR_output/Inputfiles/pheno.bayescanout.fst`

When I run, 
`selectionanalyses(do_meta=F,
do_pairwise=T,
do_outflank=F,
do_pcadapt=T,
do_fsthet=T,
add_bayescan=T,
export_data=T,
export='pdf')`

It returns,
> ERROR: the inputfiles directory does not contain files with the extension 'bayescanout.fst'.

The pheno.bayescanout.fst looks like 
>    prob  log10(PO)   qval  alpha  fst
> 1  0.00080016 -3.09648 0.782708 -0.00073201 0.23449
> 2  0.00040008 -3.3977 0.86715 0.00021504 0.23462

Any things I can do to fix it?

Thanks,
Ming

**Comment by mennodejong1986** [comment]
Thanks for reporting the issue.
I just uploaded SambaR_v1.08.txt again with a minor edit (but same name as before).
Could you try again with that new file (so first source this file)?

SambaR now runs the following commands to check if the file is present:

setwd(mysambar$inputfilesdir)
mybayefiles <- list.files(pattern = ".*.bayescanout.fst")
length(mybayefiles)<1

If you run this command, it should evaluate to FALSE, and thus not print the error message. You can try for yourself first.

Hope it works. The use of Bayescan output by SambaR has not been tested for a while.



Verzonden vanuit Outlook<http://aka.ms/weboutlook>

________________________________
Van: mimingcui ***@***.***>
Verzonden: vrijdag 6 januari 2023 20:24
Aan: mennodejong1986/SambaR ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [mennodejong1986/SambaR] unable to add Bayescan output (Issue #28)


Hi! I'm glad that I stumbled onto this all-in-one R package for population genetics analyses. The user manual is very detailed. Way to go! It'd be so convinient if eventally all the bugs will be fixed. I hope it will gain more users.

I'm currently running selection analysis and added the Bayescan output in the SambaR inputfiles directory as
./myWorkDir/SambaR_output/Inputfiles/pheno.bayescanout.fst

When I run,
selectionanalyses(do_meta=F, do_pairwise=T, do_outflank=F, do_pcadapt=T, do_fsthet=T, add_bayescan=T, export_data=T, export='pdf')

It returns,

ERROR: the inputfiles directory does not contain files with the extension 'bayescanout.fst'.

The pheno.bayescanout.fst looks like

prob log10(PO) qval alpha fst
1 0.00080016 -3.09648 0.782708 -0.00073201 0.23449
2 0.00040008 -3.3977 0.86715 0.00021504 0.23462

Any things I can do to fix it?

Thanks,
Ming

**Comment by mimingcui** [comment]
My issue with SambaR_v1.08.txt (both the previous and the newly updated one) is at function 
`genlight2sambar(genlight_object='genlight',do_confirm=TRUE)`

It would return error
> Creating inds2 dataframe...
> ERROR: unexpected number of rows of inds2 dataframe after merging with indstemp1. Contact developer of SambaR.
> ERROR: NA-values in inds2$indpair column.

So I used SambaR_v1.07.txt in the first place. It didn't report issue with _genlight2sambar_ and _filterdata_ , until when I ran _selectionanalyses_ with _add_bayescan=T_.

Thank you for your time on this.

**Comment by mennodejong1986** [comment]
I suspect that your dataset contains duplicated sample names (see @ind.names of your input genlight object).
I just uploaded Sambar_v1.08.txt again. This will now give you a more informative error message if indeed the problem is caused by duplicated sample names.

**Comment by mimingcui** [comment]
Thanks for the update. But I got the same error message and I found no duplicated sample names. 

Strange that it worked with Sambar_v1.07.txt for the most part though. I will stick with that version for now.

**Comment by mennodejong1986** [comment]
In that case I need a bit more information to solve the issue.

Could you run the following commands:
indstemp1<- inds[,c("name","pop","popcol","pop2")]
write.table(indstemp1,"indsdf.txt",col.names=TRUE,quote=FALSE,sep="\t",row.names=FALSE)

These commands will export to your working directory a file called 'indsdf.txt". If you like, you could attach this file in the following comment, so I can try to reproduce and solve the error.

**Comment by mimingcui** [comment]
Sure, here it is the file. Please check it out. Thanks!
[indsdf.txt](https://github.com/mennodejong1986/SambaR/files/10393422/indsdf.txt)

**Comment by mennodejong1986** [comment]
Thanks for sending me the file. Unfortunately, I still cannot reproduce the error.
That means I need more information to work with. 

Could you reproduce the error (using SambaR_v1.08.txt) and then, directly after the error occurred, run the following two commands?

write.table(inds,"indsall.txt",col.names=TRUE,quote=FALSE,sep="\t",row.names=FALSE)

This will export to your working directory a new file called 'indsall.txt' Would you mind sending me this file as well? Thanks!

**Comment by mennodejong1986** [comment]
So, only one command, not two.

**Comment by mimingcui** [comment]
Here is [indsall.txt](https://github.com/mennodejong1986/SambaR/files/10395448/indsall.txt)
Thanks!

**Comment by mennodejong1986** [comment]
Unfortunately I still did not manage to reproduce the error. The following commands (with a dummy dataset, but with your sample information) work fine for me:
x				<- read.table("indsall.txt",header=TRUE)
mygl			<- as.genlight(matrix(sample(c(0,1),nrow(x)*100,replace=TRUE),nrow=nrow(x),ncol=100))
mygl@ind.names	<- x$name
pop(mygl)		<- x$pop
genlight2sambar(genlight_object="mygl")

I just uploaded a new version of SambaR_v1.08.txt with some minor edits. Would you mind importing your data again using the genlight2sambar function? If you run into the same error, you will find afterwards in the working directory three files called 'indstemp1.txt', 'inds2.txt' and 'inds2merged.txt'. Could you send me those files to me as well?

Apologies for the inconvenience, but let's get this error fixed!

**Comment by mimingcui** [comment]
No problem. Thanks a lot for following up this issue. 
Here are the files.
[indstemp1.txt](https://github.com/mennodejong1986/SambaR/files/10402972/indstemp1.txt)
[inds2.txt](https://github.com/mennodejong1986/SambaR/files/10402973/inds2.txt)
[inds2merged.txt](https://github.com/mennodejong1986/SambaR/files/10402974/inds2merged.txt)

If you still couldn't reproduce the error. Please see [here](https://ulavaldti-my.sharepoint.com/:f:/g/personal/mmcui_ulaval_ca/En025wrjJmBOh3wIQJcAh5IBXc3GPpyXjI4OPHx9IXNleg?email=mennodejong1%40hotmail.com&e=7PfvAY) where I shared the genotype data. I think this could be easier for you.

**Comment by mimingcui** [comment]
It worked with the new script SambaR_v1.08.txt. With this version, it's also able to detect and read the bayescan file. Thank you so much!
