### ISSUE TITLE
SambaR not recognizing my .raw file

### ISSUE THREAD

**Issue by TaylorLBurke** [mennodejong1986/SambaR#4]
Hello, 

I am trying to import my data from a .raw file. I have my directory set correctly and have the prefix set correctly, and yet SambaR is looking for a .bim file? This is not included in the manual. Can you provide some guidance? I have attached a photo below.

![image](https://user-images.githubusercontent.com/78272985/110440442-17758f80-80d2-11eb-91c5-542fac886396.png)

**Comment by mennodejong1986** [comment]
Hi Taylor, 

The bim file will/should be generated together with the raw file, when you run PLINK. 

The command, to be executed on either Unix or Windows command line, looks like this:
plink --file prefix –-chr-set 95 –-allow-extra-chr --make-bed --recode A --out prefix

The make-bed flag tells the software to make the bim file. The ‘recode A’ flag tells the software to create the raw file. 
Make sure to have the raw and bim file stored in the same directory when trying to import them into R. They should also have the same prefix, with normally is the case.

Hope this helps!

**Comment by TaylorLBurke** [comment]
Hey! 
This did help, thank you! I was under the impression you could use either a .raw file OR a .bim file. I will add that in the version of plink I have (PLINK v1.90b6.21) you cannot run the --make-bed command as well as the --recodeA command. These need to be done in two separate steps. 

Thanks again! 
Taylor
