### ISSUE TITLE
SambaR Error: Structure command- Will not perform Mantel Tests. Error on line #11665

### ISSUE THREAD

**Issue by TaylorLBurke** [mennodejong1986/SambaR#5]
Hello, 
I am using SambaR to analyze three different datasets that correspond to three different marine invertebrate species. All of my populations only have one (typically) geographic location (I do not have the exact long and lat co-ordinates for each individual sampled). When I run the command "findstructure(Kmax=6,add_legend=TRUE,legend_pos="bottomright",legend_cex=2,pop_order=NULL)" command on one of my datasets, I run into this error: 

Creating geographical maps with admixture piecharts using LEA output...
No clear agreement between geographic locations of predefined populations and those of the inferred clusters.
Defaulting to random colour assignment.
Only 1 geographical position found for DC population. Skipping.
Only 1 geographical position found for DUR population. Skipping.
Only 1 geographical position found for MAK population. Skipping.
Only 1 geographical position found for NAIN population. Skipping.
Only 1 geographical position found for PAC population. Skipping.
Only 1 geographical position found for DC population. Skipping.
Only 1 geographical position found for DUR population. Skipping.
Only 1 geographical position found for MAK population. Skipping.
Only 1 geographical position found for NAIN population. Skipping.
Only 1 geographical position found for PAC population. Skipping.  (REPEATED)
Creating mantel plot...

**Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'ncol': object 'combitable' not found**

I suspected this may be do to not having individual long and lat co-ordinates, but
I don't have this error on my other two data sets (run into a different error later on). I'm not sure how to fix the error since it seems to not create the combitable for this dataset and I'd really like to have the results of a Mantel test for this dataset.  I will note that when running the filterdata command, I received this error:  
Error in stripchart.default(split(mf[[response]], mf[-response]), dlab = dlab,  : 
  invalid first argument

I am not sure if this would have an impact on analyses further down the road.

If you have any insight, it's much appreciated! Thanks for such a wonderful package. It's been very useful so far for exploring my data.

<img width="1438" alt="Screen Shot 2021-03-14 at 4 46 57 PM" src="https://user-images.githubusercontent.com/78272985/111069095-e7b8f400-84e4-11eb-88b1-fd011a5cea70.png">

**Comment by mennodejong1986** [comment]
Hi Taylor, I uploaded a new version. No guarantees, but could you try if this version does not throw this error? Also, although some of the output files are labelled 'Mantel', they simply show a linear regression between genetic distance and geographical distance. Not sure if this qualifies as a true Mantel test.
