### ISSUE TITLE
genlight to sambaR

### ISSUE THREAD

**Issue by thesnakeguy** [mennodejong1986/SambaR#8]
Hi,

First of all thanks for the wonderful package! However I have an issue with converting a genlight to a sambaR object. What I do:

```
testvcfr <- read.vcfR("path/to/vcf/filtered.vcf", verbose = FALSE)
genl <- vcfR2genlight(testvcfr)
genlight2sambar(genlight_object = "genl" , do_confirm=TRUE)
```

I get the following message: 

_Creating inds object...
Creating snps object..._
 
_WARNING: only 1 allele type specified to the minor and/or major flag.
SambaR will assume that all SNPs have the same type of minor or major allele (by default A for major and T for minor).
This does not affect subsequent analyses, except for calculation of transition-transversion ratios and GC-content.
Still, if you have the information on allele types (e.g. 1,2,3,4, or alternatively A,C,G,T, why not provide these vectors to the minor and major flags?_
 
_ERROR: unexpected allele found in bim file. Alleles should be either 1,2,3,4 or A,C,T,G (character). You can observe the alleles by typing 'myalleles'._

What could be the reason for this behavior?

Many thanks in advance,
Pablo

**Comment by mennodejong1986** [comment]
Hi Pablo, this is indeed unexpected behaviour. To get a better idea what is causing the problem, what do you get when you type 'myalleles'?

**Comment by thesnakeguy** [comment]
`myalleles`
[1] 4

The genlight object seems fine: 

`genl`
__/// GENLIGHT OBJECT /////////

 // 17 genotypes,  199,972 binary SNPs, size: 22.2 Mb
 811724 (23.88 %) missing data

 // Basic content
   @gen: list of 17 SNPbin

 // Optional content
   @ind.names:  17 individual labels
   @loc.names:  199972 locus labels
   @chromosome: factor storing chromosomes of the SNPs
   @position: integer storing positions of the SNPs
   @other: a list containing: elements without names__ 

Thanks for your quick response  Menno

Cheers,
Pablo

**Comment by mennodejong1986** [comment]
Hi Pablo, your data looks fine to me as well. It probably had to do with converting between different data classes. I uploaded a minute ago a new version of SambaR. Not sure if it makes matters worse or better, but could you give it a try with this new version to find out? Best, Menno

**Comment by thesnakeguy** [comment]
Hi Menno,

Thanks again for the quick reply! Now the function creates a **mygenlight** object next to the **snps** and **inds** objects. I get the following message: 

Creating inds object...
Creating snps object...
 
_WARNING: only 1 allele type specified to the minor and/or major flag.
SambaR will assume that all SNPs have the same type of minor or major allele (by default A for major and T for minor).
This does not affect subsequent analyses, except for calculation of transition-transversion ratios and GC-content.
Still, if you have the information on allele types (e.g. 1,2,3,4, or alternatively A,C,G,T, why not provide these vectors to the minor and major flags?
 
snps$minor not factor class.
snps$major not factor class.
ERROR: unexpected allele found in bim file. Alleles should be either 1,2,3,4 or A,C,T,G (character). You can observe the alleles by typing 'myalleles'._

When I try to proceed to the filterdata function it give me this:
_ERROR: Object 'mysambar' is missing. First (re)run the importdata() function and make sure it finishes without errors._

Cheers,
Pablo

**Comment by mennodejong1986** [comment]
Hi Pablo, I just uploaded yet another version. Could you give it try again? If it doesn't solve the error, at least it should give us a more informative error message. If you do run into the error again, could you let me know the class of snps$minor? (i.e. type: class(snps$minor). Thanks!

**Comment by thesnakeguy** [comment]
Hi Menno,

I just checked the new version and now everything seems to be working just fine! Many thanks for the quick fix!

Cheers,
Pablo

**Comment by mennodejong1986** [comment]
Happy to hear! Thanks for reporting the issue.
