### ISSUE TITLE
Object mypopnind not found in findstructure()

### ISSUE THREAD

**Issue by Asternosis** [mennodejong1986/SambaR#9]
Dear all,

I'm currently discovering SambaR, this seems a very great and simple method for population structure analyses!

However, I'm facing to an issue with the findstructure() function that I cannot resolve. I successed in importing and filtrate my data, respectively with importdata() and filterdata() functions. 

My findstructure() function was used as following :
`findstructure(Kmax=6,add_legend=TRUE,legend_pos="right",legend_cex=2,pop_order=NULL, do_subsets=FALSE)
`

The pipeline works and produces some plots (wahlund effect plot, pcoa plot, NJ/upgma trees...), until I enter in the DAPC analysis. There is some calculations with different K values and generates some plots, but I have finally an error because one object is not found, named "mypopnind".

`Error in findstructure(Kmax = 6, add_legend = TRUE, legend_pos = "right",  : 
  object 'mypopnind' not found`

Can you please explain me the origin and the possible fix of this error ?

Thanks a lot !

Asternosis

**Comment by mennodejong1986** [comment]
Hi Asternosis, thanks for reporting the issue, and apologies for my late reply. I uploaded a new version of SambaR a minute ago. Could you try it again with this version?

**Comment by Asternosis** [comment]
Hi Mennodejong1986,

You're welcome, don't worry !

I tested your new version of SambaR. I have now another error:

`Error in myassign[i, ] <- myprop3df[nrow(myprop3df), ] : 
  number of items to replace is not a multiple of replacement length`

Best,

Asternosis

**Comment by mennodejong1986** [comment]
This error is related to the the Bayesian population assignment test.
I will look into this issue later. For now, you can skip this analysis by setting the flag doBAPT to FALSE. Thus:

findstructure(doBAPT=FALSE)

Best,

Menno


Verzonden vanuit Outlook<http://aka.ms/weboutlook>

________________________________
Van: Asternosis ***@***.***>
Verzonden: maandag 17 mei 2021 10:51
Aan: mennodejong1986/SambaR ***@***.***>
CC: mennodejong1986 ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [mennodejong1986/SambaR] Object mypopnind not found in findstructure() (#9)


Hi Mennodejong1986,

You're welcome, don't worry !

I tested your new version of SambaR. I have now another error:

Error in myassign[i, ] <- myprop3df[nrow(myprop3df), ] : number of items to replace is not a multiple of replacement length

Best,

Asternosis

**Comment by Asternosis** [comment]
Perfect Mennodejong1986, I have no more error when option doBAPT = FALSE!

Thanks a lot for your quick and precise answers!

Best,

Asternosis
